server {
    listen ${PORT};
    server_name _;

    # 青龙主界面
    location / {
        proxy_pass http://127.0.0.1:5700;
    }

    # code-server
    location /coder/ {
        proxy_pass http://127.0.0.1:10001/;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
    }
}
